# Fetch a temporary authentication token for the Kubernetes provider
# This data source is crucial for authenticating to the EKS cluster API.
data "aws_eks_cluster_auth" "this" {
  name = module.eks.cluster_name
}

# --- Kubernetes Provider Configuration ---
# This block tells Terraform how to talk to the EKS control plane.

provider "kubernetes" {
  # EKS API Endpoint
  host                   = module.eks.cluster_endpoint
  # Base64 encoded certificate authority data
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
  # Temporary token generated by aws_eks_cluster_auth
  token                  = data.aws_eks_cluster_auth.this.token
}

# --- Helm Provider Configuration ---
# Note: The Helm provider implicitly uses the 'kubernetes' provider defined above.

# If you need to explicitly define the Helm provider (only necessary if using aliases)
# provider "helm" {
#   kubernetes {
#     host                   = module.eks.cluster_endpoint
#     cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)
#     token                  = data.aws_eks_cluster_auth.this.token
#   }
# }


# --- AWS Load Balancer Controller Helm Release ---

resource "helm_release" "aws_load_balancer_controller" {
  repository = "https://aws.github.io/eks-charts"
  chart      = "aws-load-balancer-controller"
  name       = "aws-load-balancer-controller"
  namespace  = "kube-system"
  wait       = true

  set {
    name  = "clusterName"
    value = var.cluster_name
  }
  
  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = aws_iam_role.alb_controller_irsa.arn
  }
  
  # 2. Setting the Service Account Annotation (IRSA)
  # This uses double backslashes to ensure the Helm chart receives the correctly escaped name.

  
  # 1. Setting clusterName
  #set {
   # name  = "clusterName"
   # value = var.cluster_name
  #}
  
  # 2. Setting the Service Account Annotation (IRSA)
  # This uses double backslashes to ensure the Helm chart receives the correctly escaped name.
  #set {
  #  name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
   # value = aws_iam_role.alb_controller_irsa.arn
  #}
}